server.port=8080

# spring.datasource.url=jdbc:postgresql://localhost:5432/mymobileapp
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5432/athlete_training}
spring.datasource.username=${DB_USERNAME:karasdev}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Override via env: JWT_SECRET
jwt.secret=${JWT_SECRET:dev-change-me-use-long-random-string-at-least-256-bits-for-hs256}
jwt.expiration-ms=86400000
